apiVersion: apps/v1
kind: Deployment
metadata:
  name: glusterfs-client-provisioner
  labels:
    app: glusterfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: glusterfs-client-provisioner
  template:
    metadata:
      labels:
        app: glusterfs-client-provisioner
    spec:
      serviceAccountName: glusterfs-client-provisioner
      containers:
        - name: glusterfs-client-provisioner
          image: olliai/glusterfs-client-provisioner:latest
          volumeMounts:
            - name: glusterfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/glusterfs
            - name: GLUSTERFS_ENDPOINTS
              value: 10.10.10.60:volume
            - name: GLUSTERFS_PATH
              value: /kubedata
      volumes:
        - name: glusterfs-client-root
          glusterfs:
            endpoints: 10.10.10.60:volume
            path: /kubedata
