apiVersion: apps/v1
kind: Deployment
metadata:
  name: glusterfs-client-provisioner
  labels:
    app: glusterfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: glusterfs-client-provisioner
  template:
    metadata:
      labels:
        app: glusterfs-client-provisioner
    spec:
      serviceAccountName: glusterfs-client-provisioner
      containers:
        - name: glusterfs-client-provisioner
          image: quay.io/external_storage/glusterfs-client-provisioner-arm:latest
          volumeMounts:
            - name: glusterfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: GLUSTERFS_ENDPOINTS
              value: 10.10.10.60
            - name: GLUSTERFS_PATH
              value: /ifs/kubernetes
      volumes:
        - name: glusterfs-client-root
          glusterfs:
            endpoints: 10.10.10.60
            path: /ifs/kubernetes
