kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-client-provisioner
  labels:
    app: glusterfs-client-provisioner
subsets:
- addresses:
  - ip: x.x.x.x
  ports:
  - port: 1
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-client-provisioner
  labels:
    app: glusterfs-client-provisioner
spec:
  ports: []
  clusterIP: None
  type: ClusterIP
