kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: glusterfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: glusterfs-client-provisioner
    spec:
      serviceAccountName: glusterfs-client-provisioner
      containers:
        - name: glusterfs-client-provisioner
          image: quay.io/external_storage/glusterfs-client-provisioner:latest
          volumeMounts:
            - name: glusterfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: GLUSTERFS_ENDPOINTS
              value: 10.10.10.60
            - name: GLUSTERFS_PATH
              value: /ifs/kubernetes
      volumes:
        - name: glusterfs-client-root
          glusterfs:
            endpoints: 10.10.10.60
            path: /ifs/kubernetes
